const PRE_PATH = '../assets/images/'

export default  {
    logo: require(PRE_PATH + 'coach.png'),
    crm: require(PRE_PATH + 'crm.png'),
    digital: require(PRE_PATH + 'digital.png'),
    ui: require(PRE_PATH + 'ui.png'),
    ui_course: require(PRE_PATH + 'uiCourse.png'),
    ui_detail: require(PRE_PATH + 'uiDetail.png'),
    woman_login: require(PRE_PATH + 'womanLogin.png'),
    forget: require(PRE_PATH + 'forget.png'),
    register: require(PRE_PATH + 'register.png'),
    profile: require(PRE_PATH + 'profile.png'),
    marketing: require(PRE_PATH + 'marketing.png'),
    uxDesign: require(PRE_PATH + 'uxDesign.png'),
    icon_interest: require(PRE_PATH + 'iconInterest.png'),
    icon_course: require(PRE_PATH + 'iconCourse.png'),
    icon_goal: require(PRE_PATH + 'iconGoal.png'),
    icon_chat: require(PRE_PATH + 'iconChat.png'),
    icon_settings: require(PRE_PATH + 'iconSettings.png'),
    roadmap: require(PRE_PATH + 'roadmap.png'),
    ux_cover: require(PRE_PATH + 'uxCover.png'),
    plus: require(PRE_PATH + 'plus.png'),
    flag: require(PRE_PATH + 'flag.png'),
}